In [0]:
import numpy as np
import pandas as pd

In [0]:
df=pd.read_csv('CSV 1.csv')

In [98]:
df.head()

id        city country          fullStreetAddress postalCode  \
0  2698139   St Peters      US     12 Legacy Estates Lane      63376   
1  2698093    St Louis      US          222 Euclid Avenue      63119   
2  2698007     Ballwin      US  741 Woodside Trails Drive      63021   
3  2697963  Manchester      US           301 Wembley Lane      63021   
4  2697938    O'fallon      US           27 Clear Meadows      63366   

  stateOrProvince unitNumber  bathrooms  bedrooms  \
0              MO        NaN          6         5   
1              MO        NaN          2         3   
2              MO        NaN          3         3   
3              MO        NaN          2         3   
4              MO        NaN          4         4   

                                  listingDescription   ...    yearBuilt  \
0  Tucked away in the private Legacy Estates subd...   ...       1998.0   
1  This charming Ranch offers hardwood flooring o...   ...       1962.0   
2  This is the LARGEST Villa-style condo in this ...   ...       1986.0   
3  Over 1700 sq ft of updated living space in con...   ...       1969.0   
4  Move in ready, excellent condition. Outstandin...   ...       2007.0   

    lotSize  lotSizeUnit         propertySubType  listingCategory  \
0       NaN   squareFoot  Single Family Detached         Purchase   
1   7753.68   squareFoot  Single Family Detached         Purchase   
2  14766.84   squareFoot             Condominium         Purchase   
3  11848.32   squareFoot  Single Family Detached         Purchase   
4  10890.00   squareFoot  Single Family Detached         Purchase   

  numParkingSpaces                   createdAt  geocodioAccuracyScore  \
0              3.0  2019-02-21 14:53:27.462+00                    NaN   
1              1.0   2019-02-21 14:53:07.92+00                    NaN   
2              2.0  2019-02-21 14:52:30.126+00                    NaN   
3              2.0   2019-02-21 14:52:11.85+00                    NaN   
4              3.0  2019-02-21 14:51:55.495+00                    NaN   

  photoscount    grade  
0          29  awesome  
1          29  awesome  
2          29  awesome  
3          29  awesome  
4          29  awesome  

[5 rows x 26 columns]

In [99]:
df.describe()

id   bathrooms    bedrooms    latitude   longitude  \
count  9.000000e+02  900.000000  900.000000  789.000000  789.000000   
mean   1.379640e+06    2.220000    2.948889   36.058472  -88.433106   
std    8.350904e+05    1.359857    2.110319    5.520729   13.363031   
min    2.637000e+03    0.000000    0.000000   18.385107 -157.877612   
25%    6.939698e+05    1.000000    2.000000   32.650636  -94.836975   
50%    1.362506e+06    2.000000    3.000000   36.053461  -84.288388   
75%    2.034228e+06    3.000000    4.000000   40.744408  -80.175833   
max    2.698139e+06   13.000000   51.000000   48.093560  -66.163046   

          listPrice    livingArea    yearBuilt       lotSize  \
count  9.000000e+02    726.000000   791.000000  5.620000e+02   
mean   4.455732e+05   2084.289256  1979.609355  1.224170e+05   
std    4.869270e+06   4154.019862    44.355673  1.110570e+06   
min    2.850000e+02      0.000000  1111.000000  0.000000e+00   
25%    6.497500e+04   1233.000000  1962.000000  6.534000e+03   
50%    1.999000e+05   1684.000000  1987.000000  1.043262e+04   
75%    3.399250e+05   2289.500000  2005.000000  2.178000e+04   
max    1.450000e+08  99971.000000  2019.000000  1.899216e+07   

       numParkingSpaces  geocodioAccuracyScore  photoscount  
count        460.000000              27.000000   900.000000  
mean           3.919565               0.952963    18.700000  
std           46.660458               0.158012    16.242976  
min            0.000000               0.330000     0.000000  
25%            1.000000               1.000000     1.000000  
50%            2.000000               1.000000    19.000000  
75%            2.000000               1.000000    30.000000  
max         1002.000000               1.000000    91.000000

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 26 columns):
id                       900 non-null int64
city                     900 non-null object
country                  900 non-null object
fullStreetAddress        900 non-null object
postalCode               900 non-null object
stateOrProvince          899 non-null object
unitNumber               118 non-null object
bathrooms                900 non-null int64
bedrooms                 900 non-null int64
listingDescription       842 non-null object
listingTitle             900 non-null object
latitude                 789 non-null float64
longitude                789 non-null float64
listPrice                900 non-null float64
livingArea               726 non-null float64
livingAreaUnit           900 non-null object
yearBuilt                791 non-null float64
lotSize                  562 non-null float64
lotSizeUnit              900 non-null object
propertySubType          900 non-null

In [101]:
df.drop(['id'],axis=1,inplace=True)
df.head()

city country          fullStreetAddress postalCode stateOrProvince  \
0   St Peters      US     12 Legacy Estates Lane      63376              MO   
1    St Louis      US          222 Euclid Avenue      63119              MO   
2     Ballwin      US  741 Woodside Trails Drive      63021              MO   
3  Manchester      US           301 Wembley Lane      63021              MO   
4    O'fallon      US           27 Clear Meadows      63366              MO   

  unitNumber  bathrooms  bedrooms  \
0        NaN          6         5   
1        NaN          2         3   
2        NaN          3         3   
3        NaN          2         3   
4        NaN          4         4   

                                  listingDescription  \
0  Tucked away in the private Legacy Estates subd...   
1  This charming Ranch offers hardwood flooring o...   
2  This is the LARGEST Villa-style condo in this ...   
3  Over 1700 sq ft of updated living space in con...   
4  Move in ready, excellent condition. Outstandin...   

                                        listingTitle   ...     yearBuilt  \
0           Residential, Traditional - St Peters, MO   ...        1998.0   
1      Residential, Traditional,Ranch - St Louis, MO   ...        1962.0   
2             Traditional,Ranch, Condo - Ballwin, MO   ...        1986.0   
3  Traditional,Split Foyer, Residential - Manches...   ...        1969.0   
4            Residential, Traditional - O'Fallon, MO   ...        2007.0   

    lotSize  lotSizeUnit         propertySubType listingCategory  \
0       NaN   squareFoot  Single Family Detached        Purchase   
1   7753.68   squareFoot  Single Family Detached        Purchase   
2  14766.84   squareFoot             Condominium        Purchase   
3  11848.32   squareFoot  Single Family Detached        Purchase   
4  10890.00   squareFoot  Single Family Detached        Purchase   

   numParkingSpaces                   createdAt geocodioAccuracyScore  \
0               3.0  2019-02-21 14:53:27.462+00                   NaN   
1               1.0   2019-02-21 14:53:07.92+00                   NaN   
2               2.0  2019-02-21 14:52:30.126+00                   NaN   
3               2.0   2019-02-21 14:52:11.85+00                   NaN   
4               3.0  2019-02-21 14:51:55.495+00                   NaN   

  photoscount    grade  
0          29  awesome  
1          29  awesome  
2          29  awesome  
3          29  awesome  
4          29  awesome  

[5 rows x 25 columns]

In [102]:
df.info()
df.drop(['fullStreetAddress'],axis=1,inplace=True)
df.drop(['stateOrProvince'],axis=1,inplace=True)
df.drop(['unitNumber'],axis=1,inplace=True)
df.drop(['listingDescription'],axis=1,inplace=True)
df.drop(['listingTitle'],axis=1,inplace=True)
df.drop(['latitude'],axis=1,inplace=True)
df.drop(['longitude'],axis=1,inplace=True)
df.drop(['geocodioAccuracyScore'],axis=1,inplace=True)

df.drop(['yearBuilt'],axis=1,inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 25 columns):
city                     900 non-null object
country                  900 non-null object
fullStreetAddress        900 non-null object
postalCode               900 non-null object
stateOrProvince          899 non-null object
unitNumber               118 non-null object
bathrooms                900 non-null int64
bedrooms                 900 non-null int64
listingDescription       842 non-null object
listingTitle             900 non-null object
latitude                 789 non-null float64
longitude                789 non-null float64
listPrice                900 non-null float64
livingArea               726 non-null float64
livingAreaUnit           900 non-null object
yearBuilt                791 non-null float64
lotSize                  562 non-null float64
lotSizeUnit              900 non-null object
propertySubType          900 non-null object
listingCategory          900 non-nul

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 16 columns):
city                900 non-null object
country             900 non-null object
postalCode          900 non-null object
bathrooms           900 non-null int64
bedrooms            900 non-null int64
listPrice           900 non-null float64
livingArea          726 non-null float64
livingAreaUnit      900 non-null object
lotSize             562 non-null float64
lotSizeUnit         900 non-null object
propertySubType     900 non-null object
listingCategory     900 non-null object
numParkingSpaces    460 non-null float64
createdAt           900 non-null object
photoscount         900 non-null int64
grade               900 non-null object
dtypes: float64(4), int64(3), object(9)
memory usage: 112.6+ KB


In [0]:
df['createdAt'] = df['createdAt'].astype('category')
df['listingCategory'] = df['listingCategory'].astype('category')
df['propertySubType'] = df['propertySubType'].astype('category')
df['lotSizeUnit'] = df['lotSizeUnit'].astype('category')
df['livingAreaUnit'] = df['livingAreaUnit'].astype('category')

df['postalCode'] = df['postalCode'].astype('category')
df['country'] = df['country'].astype('category')
df['city'] = df['city'].astype('category')


In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 16 columns):
city                900 non-null category
country             900 non-null category
postalCode          900 non-null category
bathrooms           900 non-null int64
bedrooms            900 non-null int64
listPrice           900 non-null float64
livingArea          726 non-null float64
livingAreaUnit      900 non-null category
lotSize             562 non-null float64
lotSizeUnit         900 non-null category
propertySubType     900 non-null category
listingCategory     900 non-null category
numParkingSpaces    460 non-null float64
createdAt           900 non-null category
photoscount         900 non-null int64
grade               900 non-null object
dtypes: category(8), float64(4), int64(3), object(1)
memory usage: 165.1+ KB


In [0]:
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)

In [107]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 16 columns):
city                900 non-null int16
country             900 non-null int8
postalCode          900 non-null int16
bathrooms           900 non-null int64
bedrooms            900 non-null int64
listPrice           900 non-null float64
livingArea          726 non-null float64
livingAreaUnit      900 non-null int8
lotSize             562 non-null float64
lotSizeUnit         900 non-null int8
propertySubType     900 non-null int8
listingCategory     900 non-null int8
numParkingSpaces    460 non-null float64
createdAt           900 non-null int16
photoscount         900 non-null int64
grade               900 non-null object
dtypes: float64(4), int16(3), int64(3), int8(5), object(1)
memory usage: 66.0+ KB


In [0]:
df=df.fillna(df.mean())

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 16 columns):
city                900 non-null int16
country             900 non-null int8
postalCode          900 non-null int16
bathrooms           900 non-null int64
bedrooms            900 non-null int64
listPrice           900 non-null float64
livingArea          900 non-null float64
livingAreaUnit      900 non-null int8
lotSize             900 non-null float64
lotSizeUnit         900 non-null int8
propertySubType     900 non-null int8
listingCategory     900 non-null int8
numParkingSpaces    900 non-null float64
createdAt           900 non-null int16
photoscount         900 non-null int64
grade               900 non-null object
dtypes: float64(4), int16(3), int64(3), int8(5), object(1)
memory usage: 66.0+ KB


In [110]:
df=pd.get_dummies(df,columns=['grade'])

df.drop(['lotSizeUnit'],axis=1,inplace=True)
df.drop(['livingAreaUnit'],axis=1,inplace=True)
df.head()

city  country  postalCode  bathrooms  bedrooms  listPrice  livingArea  \
0   538        2         508          6         5   425000.0      3046.0   
1   537        2         505          2         3   175000.0      1587.0   
2    29        2         500          3         3   295000.0      2437.0   
3   330        2         500          2         3   215000.0      1780.0   
4   401        2         507          4         4   375000.0      3405.0   

         lotSize  propertySubType  listingCategory  numParkingSpaces  \
0  122417.000783                9                0               3.0   
1    7753.680000                9                0               1.0   
2   14766.840000                1                0               2.0   
3   11848.320000                9                0               2.0   
4   10890.000000                9                0               3.0   

   createdAt  photoscount  grade_awesome  grade_bad  grade_good  
0        899           29              1          0           0  
1        898           29              1          0           0  
2        897           29              1          0           0  
3        896           29              1          0           0  
4        895           29              1          0           0

In [112]:
df1=df.iloc[:,0:13]
df1.head()

city  country  postalCode  bathrooms  bedrooms  listPrice  livingArea  \
0   538        2         508          6         5   425000.0      3046.0   
1   537        2         505          2         3   175000.0      1587.0   
2    29        2         500          3         3   295000.0      2437.0   
3   330        2         500          2         3   215000.0      1780.0   
4   401        2         507          4         4   375000.0      3405.0   

         lotSize  propertySubType  listingCategory  numParkingSpaces  \
0  122417.000783                9                0               3.0   
1    7753.680000                9                0               1.0   
2   14766.840000                1                0               2.0   
3   11848.320000                9                0               2.0   
4   10890.000000                9                0               3.0   

   createdAt  photoscount  
0        899           29  
1        898           29  
2        897           29  
3        896           29  
4        895           29

In [113]:
df2=df.iloc[:,13:]
df2.head()

grade_awesome  grade_bad  grade_good
0              1          0           0
1              1          0           0
2              1          0           0
3              1          0           0
4              1          0           0

In [114]:
X=np.array(df1)
y=np.array(df2)
X[1]

array([5.37000e+02, 2.00000e+00, 5.05000e+02, 2.00000e+00, 3.00000e+00,
       1.75000e+05, 1.58700e+03, 7.75368e+03, 9.00000e+00, 0.00000e+00,
       1.00000e+00, 8.98000e+02, 2.90000e+01])

In [115]:
df1.isnull().any()
X[1]

array([5.37000e+02, 2.00000e+00, 5.05000e+02, 2.00000e+00, 3.00000e+00,
       1.75000e+05, 1.58700e+03, 7.75368e+03, 9.00000e+00, 0.00000e+00,
       1.00000e+00, 8.98000e+02, 2.90000e+01])

In [116]:
np.linalg.norm(X,axis=0)


array([1.05250770e+04, 5.99082632e+01, 1.35115344e+04, 7.80896920e+01,
       1.08765803e+02, 1.46607572e+08, 1.28141911e+05, 2.65594595e+07,
       2.47455046e+02, 1.10453610e+01, 1.00655885e+03, 1.55754663e+04,
       7.42905108e+02])

In [117]:
X=X/np.linalg.norm(X,axis=0)
X[1]

array([0.051021  , 0.03338438, 0.03737547, 0.02561157, 0.0275822 ,
       0.00119366, 0.01238471, 0.00029194, 0.03637024, 0.        ,
       0.00099348, 0.05765477, 0.03903594])

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation,Dropout

In [119]:
X[1]

array([0.051021  , 0.03338438, 0.03737547, 0.02561157, 0.0275822 ,
       0.00119366, 0.01238471, 0.00029194, 0.03637024, 0.        ,
       0.00099348, 0.05765477, 0.03903594])

In [0]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=13))
model.add(Dropout(0.5))
model.add(Dense(16,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

In [0]:
from keras.optimizers import Adam

model.compile(loss='mean_squared_error',
              optimizer=Adam(),
              metrics=['accuracy'])


In [129]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_23 (Dense)             (None, 32)                448       
_________________________________________________________________
dropout_13 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_24 (Dense)             (None, 16)                528       
_________________________________________________________________
dropout_14 (Dropout)         (None, 16)                0         
_________________________________________________________________
dense_25 (Dense)             (None, 3)                 51        
Total params: 1,027
Trainable params: 1,027
Non-trainable params: 0
_________________________________________________________________


In [130]:
model.fit(X,y,epochs=20,steps_per_epoch=2000)

Epoch 1/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0896 - acc: 0.8215
Epoch 2/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0421 - acc: 0.9244
Epoch 3/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0337 - acc: 0.9406
Epoch 4/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0304 - acc: 0.9463
Epoch 5/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0286 - acc: 0.9494
Epoch 6/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0273 - acc: 0.9515
Epoch 7/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0267 - acc: 0.9524
Epoch 8/20
2000/2000 [==============================] - 5s 2ms/step - loss: 0.0262 - acc: 0.9533
Epoch 9/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0260 - acc: 0.9535
Epoch 10/20
2000/2000 [==============================] - 5s 3ms/step - loss: 0.0257 - acc: 0.9540
Epoch 11/20
2000/2000 [======

In [0]:
pred=model.predict(X)

In [132]:
pred

array([[1.0000000e+00, 0.0000000e+00, 2.6663152e-08],
       [9.9999738e-01, 0.0000000e+00, 2.6003167e-06],
       [9.9995148e-01, 0.0000000e+00, 4.8514215e-05],
       ...,
       [0.0000000e+00, 1.0000000e+00, 2.0535342e-08],
       [0.0000000e+00, 1.0000000e+00, 4.1256678e-09],
       [0.0000000e+00, 1.0000000e+00, 5.2459410e-09]], dtype=float32)

In [135]:
names=['grade_awesome','grade_bad','grade_good']
a=np.argmax(pred[0])
names[a]

'grade_awesome'

In [0]:
model.save('my_model.h5')
